#!/usr/bin/env python3
"""
EEZ Studio UI Import Script for ESP-IDF
========================================

Imports EEZ Studio generated files into this ESP-IDF project.

Usage:
    python import_eez_ui.py <eez_export_directory>

What it does:
  1. Backs up current main/eez_ui/ to main/eez_ui_backup/
  2. Copies all generated files from EEZ export to main/eez_ui/
  3. Fixes include paths: <lvgl/lvgl.h> -> "lvgl.h"  (ESP-IDF uses simple include)
  4. Reports what was imported

After running this script:
  - Build normally: idf.py build
  - Flash: idf.py flash
  - No additional steps needed!

Note: actions.cpp and vars.cpp contain YOUR custom logic.
      The script preserves them if they exist and only overwrites
      the EEZ-generated headers (actions.h, vars.h).
"""

import os
import sys
import stat
import shutil
import glob
import re
import time
from datetime import datetime

# Project paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
EEZ_UI_DIR = os.path.join(SCRIPT_DIR, "main", "eez_ui")
BACKUP_DIR = os.path.join(SCRIPT_DIR, "main", "eez_ui_backup")

# Files that contain user logic (preserve these)
USER_FILES = {"actions.cpp", "vars.cpp"}

def _on_rm_error(func, path, exc_info):
    """Handle rmtree errors on Windows (read-only files, locked files)."""
    # Clear read-only flag and retry
    try:
        os.chmod(path, stat.S_IWRITE | stat.S_IREAD)
        func(path)
    except Exception:
        # File might be locked by IDE — wait briefly and retry once
        time.sleep(0.5)
        try:
            os.chmod(path, stat.S_IWRITE | stat.S_IREAD)
            func(path)
        except Exception:
            print(f"  Warning: Could not remove {path} — file may be locked by another program")


def safe_rmtree(path):
    """Remove directory tree, handling Windows permission issues."""
    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=lambda fn, p, ex: _on_rm_error(fn, p, None))
    else:
        shutil.rmtree(path, onerror=_on_rm_error)


def fix_includes(filepath):
    """Fix EEZ Studio include paths for ESP-IDF compatibility.

    EEZ Studio generates: #include <lvgl/lvgl.h>
    ESP-IDF needs:        #include "lvgl.h"
    """
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    original = content

    # Fix <lvgl/lvgl.h> -> "lvgl.h"
    content = re.sub(r'#include\s*<lvgl/lvgl\.h>', '#include "lvgl.h"', content)

    # Fix <lvgl/src/lvgl_private.h> -> "src/lvgl_private.h"
    content = re.sub(r'#include\s*<lvgl/src/lvgl_private\.h>', '#include "src/lvgl_private.h"', content)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def fix_flow_engine(filepath):
    """Fix EEZ flow engine bug: memcpy from integer user_data/param pointers.

    EEZ-generated event handlers set e->user_data to small integer values
    (e.g. (void*)1 for digit "1"). The flow engine then tries to memcpy
    from this address, causing a crash. This fix adds a pointer validity
    check before the memcpy.
    """
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    original = content

    # Fix user_data memcpy
    content = content.replace(
        'if (event->user_data) {\n'
        '        g_lastLVGLEvent.user_data = &g_lastLVGLEventUserDataBuffer;\n'
        '        memcpy(&g_lastLVGLEventUserDataBuffer, event->user_data, sizeof(g_lastLVGLEventUserDataBuffer));',
        'if (event->user_data && (uintptr_t)event->user_data > 0x1000u) {\n'
        '        g_lastLVGLEvent.user_data = &g_lastLVGLEventUserDataBuffer;\n'
        '        memcpy(&g_lastLVGLEventUserDataBuffer, event->user_data, sizeof(g_lastLVGLEventUserDataBuffer));'
    )

    # Fix param memcpy
    content = content.replace(
        'if (event->param) {\n'
        '        g_lastLVGLEvent.param = &g_lastLVGLEventParamBuffer;\n'
        '        memcpy(&g_lastLVGLEventParamBuffer, event->param, sizeof(g_lastLVGLEventParamBuffer));',
        'if (event->param && (uintptr_t)event->param > 0x1000u) {\n'
        '        g_lastLVGLEvent.param = &g_lastLVGLEventParamBuffer;\n'
        '        memcpy(&g_lastLVGLEventParamBuffer, event->param, sizeof(g_lastLVGLEventParamBuffer));'
    )

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def main():
    if len(sys.argv) < 2:
        print("Usage: python import_eez_ui.py <eez_export_directory>")
        print()
        print("The export directory should contain the files generated by EEZ Studio:")
        print("  ui.h, ui.c, screens.h, screens.c, actions.h, vars.h, images.h, etc.")
        sys.exit(1)

    source_dir = os.path.abspath(sys.argv[1])

    if not os.path.isdir(source_dir):
        print(f"Error: '{source_dir}' is not a directory")
        sys.exit(1)

    # Check for expected EEZ files
    expected_files = ["ui.h", "ui.c", "screens.h", "screens.c"]
    found = [f for f in expected_files if os.path.exists(os.path.join(source_dir, f))]
    if not found:
        print(f"Warning: No expected EEZ files found in '{source_dir}'")
        print(f"Expected: {', '.join(expected_files)}")
        response = input("Continue anyway? [y/N] ")
        if response.lower() != 'y':
            sys.exit(0)

    print(f"Source:      {source_dir}")
    print(f"Destination: {EEZ_UI_DIR}")
    print()

    # Step 1: Backup current eez_ui
    if os.path.exists(EEZ_UI_DIR):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = f"{BACKUP_DIR}_{timestamp}"
        print(f"[1/5] Backing up current UI to: {os.path.basename(backup_path)}")
        shutil.copytree(EEZ_UI_DIR, backup_path)
    else:
        print("[1/5] No existing UI to back up")

    # Step 2: Preserve user files
    preserved = {}
    for user_file in USER_FILES:
        user_path = os.path.join(EEZ_UI_DIR, user_file)
        if os.path.exists(user_path):
            with open(user_path, 'r', encoding='utf-8', errors='ignore') as f:
                preserved[user_file] = f.read()
            print(f"       Preserving user file: {user_file}")

    # Step 3: Clear and copy new files
    print(f"[2/5] Importing EEZ Studio files...")
    if os.path.exists(EEZ_UI_DIR):
        safe_rmtree(EEZ_UI_DIR)
    os.makedirs(EEZ_UI_DIR, exist_ok=True)

    imported = []
    for item in os.listdir(source_dir):
        src = os.path.join(source_dir, item)
        dst = os.path.join(EEZ_UI_DIR, item)
        if os.path.isfile(src):
            shutil.copy2(src, dst)
            imported.append(item)
        elif os.path.isdir(src):
            shutil.copytree(src, dst)
            imported.append(f"{item}/")

    print(f"       Imported {len(imported)} items")

    # Step 4: Restore user files (if not overwritten by EEZ export)
    print(f"[3/5] Restoring user implementation files...")
    for user_file, content in preserved.items():
        user_path = os.path.join(EEZ_UI_DIR, user_file)
        # Only restore if EEZ didn't generate this file
        if not os.path.exists(user_path):
            with open(user_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"       Restored: {user_file}")
        else:
            print(f"       EEZ generated {user_file} — your version is in backup")

    # Step 5: Fix includes
    print(f"[4/5] Fixing include paths for ESP-IDF...")
    fixed_count = 0
    for ext in ("*.h", "*.c", "*.cpp"):
        for filepath in glob.glob(os.path.join(EEZ_UI_DIR, "**", ext), recursive=True):
            if fix_includes(filepath):
                fixed_count += 1
                print(f"       Fixed: {os.path.relpath(filepath, EEZ_UI_DIR)}")

    if fixed_count == 0:
        print("       No include fixes needed")

    # Step 6: Fix flow engine bug (memcpy from integer user_data)
    print(f"[5/5] Patching EEZ flow engine for ESP32...")
    flow_file = os.path.join(EEZ_UI_DIR, "eez-flow.cpp")
    if os.path.exists(flow_file):
        if fix_flow_engine(flow_file):
            print("       Patched: eez-flow.cpp (user_data pointer fix)")
        else:
            print("       No flow engine patches needed")
    else:
        print("       No eez-flow.cpp found (skipped)")

    print()
    print("=" * 60)
    print("DONE! Imported files:")
    for item in sorted(imported):
        print(f"  - {item}")
    print()
    print("Next steps:")
    print("  1. Implement your actions in main/eez_ui/actions.cpp")
    print("  2. Implement your variables in main/eez_ui/vars.cpp")
    print("  3. Build: idf.py build")
    print("  4. Flash: idf.py flash")
    print("=" * 60)

if __name__ == "__main__":
    main()
